# -*- coding: utf-8 -*-
"""Box plot in same plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woGqTOAIU5ZPlHD2H4tc2zPlrWPzJ2ev
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# File names
file_names = ["ValenceElectrons_wa_standardized_normalized.txt", "WA_atomicradii_pm_standardized_normalized.txt", "WA_CovRad_standardized_normalized.txt",
              "Wa_ElectricalConductivity_S_per_m_standardized_normalized.txt", "Wa_electronegativity_standardized_normalized.txt", "WA_ionization_0_charge_Ev_standardized_normalized.txt",
              "WA_ionization+1charge_Ev_standardized_normalized.txt", "WA_ionization+2charge_Ev_standardized_normalized.txt", "WA_ionization+3charge_Ev_standardized_normalized.txt", "WA_Ionrad_standardized_normalized.txt",
              "WA_LarPar_b_standardized_normalized.txt", "WA_LatPar_a_standardized_normalized.txt", "WA_LatPar_c_standardized_normalized.txt","Wa_ThermalConductivity_W_per_Mk_standardized_normalized.txt","z_standardized_normalized (1).txt"]

# Function to read data from a file and return a DataFrame
def read_data(file_name):
    data = pd.read_csv(file_name, header=None, names=['Value'])
    return data

# Create a subplot grid
fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(20, 10))

# Create a list to store all dataframes
all_data = []

# Iterate through file names and create box plots
for file_name in file_names:
    # Read data from file
    data = read_data(file_name)

    # Add data to the list
    all_data.append(data)

# Create box plot
sns.boxplot(data=all_data, ax=axes)
axes.set_xticklabels(file_names, rotation=45, ha="right")
axes.set_title('Box Plots of Different Datasets')
axes.set_ylabel('Value')

# Adjust layout
plt.tight_layout()

# Show the plot
plt.show()