# -*- coding: utf-8 -*-
"""standardization and normalization of compounds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-q3ll2XJTzlLgopfmGyq2G6kyhSRbDE
"""

import os
import numpy as np

# Create a folder to store the normalized data files
output_folder = "normalized_data"
os.makedirs(output_folder, exist_ok=True)

# Define the list of input files
files = [

    "T.txt"
]

# Standardize and normalize each file
for file in files:
    with open(file, 'r') as f:
        # Read data from the file, skipping empty lines
        data = [float(line.strip()) for line in f if line.strip()]

        # Z-score normalization
        z_score_normalized_data = (np.array(data) - np.mean(data)) / np.std(data)

        # Min-Max scaling
        min_max_normalized_data = (z_score_normalized_data - np.min(z_score_normalized_data)) / (
            np.max(z_score_normalized_data) - np.min(z_score_normalized_data)
        )

        # Create a new file with the standardized and normalized data
        output_file = os.path.join(output_folder, f"{file.split('.')[0]}_standardized_normalized.txt")
        with open(output_file, 'w') as output_f:
            for value in min_max_normalized_data:
                output_f.write(f"{value}\n")